'use client';

import { useEffect, useRef, useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import * as XLSX from 'xlsx';
import { Plus, Trash2, Image as ImageIcon, Hash,Layers, RefreshCw, Loader } from "lucide-react";
import { toast } from 'sonner';
import Image from 'next/image';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Attribute, Category, CreateProductPayload, ProductAttributeState } from '@/app/utils/type';


interface Variation {
  id: number;
  name: string;
  sku: string;
  barcode: string;
  costPrice: number;
  sellingPrice: number;
  quantity: number;
  threshold: number;
  images: File[];
}
interface ExcelVariant {
  name: string;
  sku: string;
  barcode: string;
  costPrice: number;
  sellingPrice: number;
  quantity: number;
  threshold: number;
  images?: string; 
}
type ExcelProductRow = {
  'Product Name': string;
  'Brand': string;
  'Category Name': string;  
  'Unit': string;
  'Taxable': string;
  'Description': string;
  'Has Variations': string;
  'Base SKU': string;
  'Cost Price'?: string;
  'Selling Price'?: string;
  'Quantity'?: string;
  'Threshold'?: string;
  'Barcode'?: string;
  'Product Images'?: string; 
  'Variants'?: string;
};


interface ValidationError {
  row?: number;
  column?: string;
  message: string;
  type: 'error' | 'warning';
}

interface ImportRowResult {
  rowNumber: number;
  productName: string;
  status: 'success' | 'failed' | 'skipped';
  message?: string;
  warning?: string;
  autoGeneratedSku?: boolean;
  autoGeneratedBarcode?: boolean;
}

interface ColumnMapping {
  [key: string]: string;
}

interface ExcelValidationResult {
  isValid: boolean;
  errors: ValidationError[];
  suggestedMapping?: ColumnMapping;
}

interface MissingImagesInfo {
  rowNumber: number;
  productName: string;
  missingImages: string[];
}

interface BulkImageCategory {
  fileName: string;
  category: 'product' | 'variant' | 'both';
}

interface ApiResponse {
  message?: string;
  product?: {
    id: string | number;
    image_url?: string[];
    [key: string]: unknown;
  };
  productId?: string | number;
  variants?: Array<{
    id: string | number;
    image_url?: string[];
    [key: string]: unknown;
  }>;
  [key: string]: unknown;
}


const calculateLevenshteinDistance = (a: string, b: string): number => {
  const aLower = a.toLowerCase();
  const bLower = b.toLowerCase();
  const matrix: number[][] = [];

  for (let i = 0; i <= bLower.length; i++) {
    matrix[i] = [i];
  }

  for (let j = 0; j <= aLower.length; j++) {
    matrix[0][j] = j;
  }

  for (let i = 1; i <= bLower.length; i++) {
    for (let j = 1; j <= aLower.length; j++) {
      if (bLower.charAt(i - 1) === aLower.charAt(j - 1)) {
        matrix[i][j] = matrix[i - 1][j - 1];
      } else {
        matrix[i][j] = Math.min(
          matrix[i - 1][j - 1] + 1,
          matrix[i][j - 1] + 1,
          matrix[i - 1][j] + 1
        );
      }
    }
  }

  return matrix[bLower.length][aLower.length];
};

const fuzzyMatchFilename = (
  searchName: string,
  availableFiles: File[],
  threshold: number = 2
): File | undefined => {
  const matches = availableFiles
    .map(file => ({
      file,
      distance: calculateLevenshteinDistance(searchName, file.name),
    }))
    .filter(({ distance }) => distance <= threshold)
    .sort((a, b) => a.distance - b.distance);

  return matches.length > 0 ? matches[0].file : undefined;
};

const validateExcelStructure = (data: Record<string, unknown>[], availableCategories: Category[]): ExcelValidationResult => {
  const requiredColumns = [
    'Product Name',
    'Brand',
    'Category Name',
    'Unit',
    'Taxable',
    'Description',
    'Has Variations',
    'Base SKU',
  ];

  const errors: ValidationError[] = [];

  if (!data || data.length === 0) {
    return {
      isValid: false,
      errors: [{ message: 'Excel file is empty or invalid', type: 'error' }],
    };
  }


  const firstRow = data[0];
  const actualColumns = Object.keys(firstRow || {});
  const missingColumns = requiredColumns.filter(col => !actualColumns.includes(col));

  if (missingColumns.length > 0) {
    errors.push({
      column: missingColumns.join(', '),
      message: `Missing required columns: ${missingColumns.join(', ')}`,
      type: 'error',
    });
  }


  const emptyRows: number[] = [];
  data.forEach((row, idx) => {
    const values = Object.values(row);
    if (!values.some(v => v && String(v).trim())) {
      emptyRows.push(idx + 2);
    }
  });

  if (emptyRows.length > 0) {
    errors.push({
      message: `Found ${emptyRows.length} empty rows at: ${emptyRows.slice(0, 5).join(', ')}${emptyRows.length > 5 ? '...' : ''}`,
      type: 'warning',
    });
  }


  data.forEach((row, idx) => {
    const categoryName = (row as Record<string, unknown>)['Category Name'];
    if (categoryName && !availableCategories.some(c => c.name.toLowerCase() === String(categoryName).toLowerCase())) {
      errors.push({
        row: idx + 2,
        message: `Category "${categoryName}" not found in system`,
        type: 'error',
      });
    }
  });

  return {
    isValid: errors.filter(e => e.type === 'error').length === 0,
    errors,
  };
};

const detectDuplicates = (data: Record<string, unknown>[]): { skus: Map<string, number[]>; names: Map<string, number[]> } => {
  const skuMap = new Map<string, number[]>();
  const nameMap = new Map<string, number[]>();

  data.forEach((row, idx) => {
    const baseSku = String((row as Record<string, unknown>)['Base SKU'] || '').trim();
    const productName = String((row as Record<string, unknown>)['Product Name'] || '').trim();

    if (baseSku) {
      skuMap.set(baseSku, [...(skuMap.get(baseSku) || []), idx + 2]);
    }
    if (productName) {
      nameMap.set(productName, [...(nameMap.get(productName) || []), idx + 2]);
    }
  });

  return {
    skus: new Map(Array.from(skuMap).filter(([, rows]) => rows.length > 1)),
    names: new Map(Array.from(nameMap).filter(([, rows]) => rows.length > 1)),
  };
};

const validateVariantJSON = (variantString: string): { isValid: boolean; parsed?: ExcelVariant[]; error?: string } => {
  try {
    const parsed = JSON.parse(variantString) as ExcelVariant[];
    if (!Array.isArray(parsed)) {
      return { isValid: false, error: 'Variants must be a JSON array' };
    }

    const requiredFields = ['sku', 'costPrice', 'sellingPrice', 'quantity', 'threshold'];
    for (const variant of parsed) {
      for (const field of requiredFields) {
        if (!(field in variant)) {
          return { isValid: false, error: `Missing required field in variant: ${field}` };
        }
      }
    }

    return { isValid: true, parsed };
  } catch (err) {
    return {
      isValid: false,
      error: err instanceof Error ? err.message : 'Invalid JSON format',
    };
  }
};


const usedBarcodes = new Set<string>();
const usedSkus = new Set<string>();

const generateUniqueBarcode = (): string => {
  let barcode: string;

  do {
    barcode = `PRD-${Date.now().toString().slice(-6)}-${Math.random()
      .toString(36)
      .slice(2, 6)
      .toUpperCase()}`;
  } while (usedBarcodes.has(barcode));

  usedBarcodes.add(barcode);
  return barcode;
};

const generateUniqueSKU = (variantName?: string, baseSku?: string): string => {
  let sku: string;

 
  if (variantName && baseSku) {
   
    const variantPart = variantName
      .toUpperCase()
      .replace(/\s+/g, '-')
      .slice(0, 10); 
    
    sku = `${variantPart}-${baseSku}`;
  } else if (baseSku) {
   
    const suffix = Math.random().toString(36).slice(2, 6).toUpperCase();
    sku = `${baseSku}-${suffix}`;
  } else {
   
    do {
      sku = `SKU-${Date.now().toString().slice(-6)}-${Math.random()
        .toString(36)
        .slice(2, 6)
        .toUpperCase()}`;
    } while (usedSkus.has(sku));
    usedSkus.add(sku);
    return sku;
  }

 
  if (usedSkus.has(sku)) {
  
    const suffix = Math.random().toString(36).slice(2, 4).toUpperCase();
    sku = `${sku}-${suffix}`;
  }

  usedSkus.add(sku);
  return sku;
};



function AttributeItem({
  attr,
  index,
  disabled,
  isNameLocked,
  updateAttributeName,
  addAttributeValue,
  removeAttribute,
  removeAttributeValue,
}: {
  attr: { name: string; values: string[] };
  index: number;
  disabled: boolean;
  isNameLocked: boolean;
  updateAttributeName: (index: number, name: string) => void;
  addAttributeValue: (index: number, value: string) => void;
  removeAttribute: (index: number) => void;
  removeAttributeValue: (attrIndex: number, valueIndex: number) => void;
}) {

  const [newValue, setNewValue] = useState("");

  

  return (
    <div className="space-y-2 border p-3 rounded-lg">
     
      <div className="flex gap-2">
        <Input
        disabled={disabled || isNameLocked}
        placeholder="Attribute name (e.g., Color)"
        value={attr.name}
        onChange={(e) =>
            updateAttributeName(index, e.target.value)
        }
        />
        {isNameLocked && (
  <p className="text-xs text-gray-500 mt-1">
    This attribute comes from system configuration
  </p>
)}

       <Button
        disabled={disabled}
        variant="destructive"
        size="icon"
        onClick={() => removeAttribute(index)}
        >
          <Trash2 className="h-4 w-4" />
        </Button>
      </div>
        
    
      <div className="flex flex-wrap gap-2">
        {attr.values.map((value, vIndex) => (
          <div
            key={vIndex}
            className="flex items-center gap-1 bg-gray-100 text-gray-900 px-3 py-1 rounded-full"
          >
            <span>{value}</span>
            <button
              className="text-gray-400 hover:text-red-500"
              onClick={() =>
                removeAttributeValue(index, vIndex)
              }
            >
              ×
            </button>
          </div>
        ))}
      </div>

     
      <div className="flex gap-2">
       <Input
        disabled={disabled}
        placeholder="Add value (e.g., Red)"
        value={newValue}
        onChange={(e) => setNewValue(e.target.value)}
        />
        <Button
         disabled={disabled}
          size="sm"
          onClick={() => {
            addAttributeValue(index, newValue);
            setNewValue("");
          }}
        >
          Add
        </Button>
      </div>
    </div>
  );
}

export default function AddProductForm() {
  const [variations, setVariations] = useState<Variation[]>([]);
  const [hasVariations, setHasVariations] = useState(false);
  const [variantsGenerated, setVariantsGenerated] = useState(false);
  const [productImages, setProductImages] = useState<File[]>([]);
  const [attributes, setAttributes] = useState<ProductAttributeState[]>([]);
  const [isCreating, setIsCreating] = useState(false);

  const [productName, setProductName] = useState<string>("");
  const [brand, setBrand] = useState<string>("");

  const [customBaseSku, setCustomBaseSku] = useState<string | null>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [categoriesLoading, setCategoriesLoading] = useState(false);
  const [availableAttributes, setAvailableAttributes] = useState<Attribute[]>([]);
  const [bulkImages, setBulkImages] = useState<FileList | null>(null);
  const [bulkImageCategories, setBulkImageCategories] = useState<BulkImageCategory[]>([]);
  const [importReport, setImportReport] = useState<ImportRowResult[]>([]);

  const [categoryId, setCategoryId] = useState<string>("");
  const [description, setDescription] = useState("");
  const [taxable, setTaxable] = useState(false);
  const [unit, setUnit] = useState("Pieces");
  const [categoryModalOpen, setCategoryModalOpen] = useState(false);
  const [newCategoryName, setNewCategoryName] = useState("");
  const [singleBarcode, setSingleBarcode] = useState<string>("");
  const imageInputRef = useRef<HTMLInputElement | null>(null);
  const excelInputRef = useRef<HTMLInputElement | null>(null);
  const bulkImagesInputRef = useRef<HTMLInputElement | null>(null);

  const [singleStock, setSingleStock] = useState({
    costPrice: 0,
    sellingPrice: 0,
    quantity: 0,
    threshold: 0,
  });


  const [uploadProgress, setUploadProgress] = useState({
    current: 0,
    total: 0,
    isUploading: false,
    currentStatus: 'validating' as 'validating' | 'processing' | 'uploading' | 'completed',
    detailedMessage: 'Preparing upload...',
    startTime: 0,
    estimatedTime: 0,
  });

  const [validationErrors, setValidationErrors] = useState<ValidationError[]>([]);
  const [showValidationDialog, setShowValidationDialog] = useState(false);
  const cancelUploadRef = useRef(false);
  const [missingImages, setMissingImages] = useState<MissingImagesInfo[]>([]);
  const [failedRows, setFailedRows] = useState<Record<string, unknown>[]>([]);

  useEffect(() => {
    const fetchCategories = async () => {
      try {
        const token = localStorage.getItem('adminToken');
        if (!token) {
          throw new Error('No authentication token found');
        }
        setCategoriesLoading(true);
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/categories`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
              'Content-Type': 'application/json',
            },
          }
        );
        const data = await res.json();
        setCategories(data);
      } catch {
        toast.error("Failed to load categories");
      } finally {
        setCategoriesLoading(false);
      }
    };

    fetchCategories();
  }, []);

const handleCreateCategory = async () => {
  if (isCreating) return;
  setIsCreating(true);
  try {
      const token = localStorage.getItem('adminToken');

      if (!token) {
        throw new Error('No authentication token found');
      }
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/categories`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({ name: newCategoryName }),
      }
    );

    if (!res.ok) throw new Error();

    const created: Category = await res.json();

    setCategories(prev => [created, ...prev]);
    setCategoryId(created.id);

    toast.success("Category created");
    setCategoryModalOpen(false);
    setNewCategoryName("");
  } catch {
    toast.error("Failed to create category");
  } finally {
    setIsCreating(false);
  }
};

useEffect(() => {
  const fetchAttributes = async () => {
    try {

        const token = localStorage.getItem('adminToken');
        if (!token) {
          throw new Error('No authentication token found');
        }
      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/attributes`,
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );
      const data = await res.json();
      setAvailableAttributes(data.attributes);
    } catch {
      toast.error("Failed to load attributes");
    }
  };

  fetchAttributes();
}, []);

useEffect(() => {
  if (!hasVariations) return;
  if (attributes.length > 0) return;
  if (availableAttributes.length === 0) return;

  setAttributes(
    availableAttributes.map(attr => ({
      id: crypto.randomUUID(),
      name: attr.name,
      attributeId: attr.id,
      values: attr.values?.map(v => v.value) ?? [],
    }))
  );
}, [availableAttributes, hasVariations, attributes.length]);

  async function handleExcelUpload(e: React.ChangeEvent<HTMLInputElement>) {
    cancelUploadRef.current = false;
    const createdProductIds: string[] = [];
    const token = localStorage.getItem("adminToken");
    const file = e.target.files?.[0];
    
    if (!file) {
      toast.error('No file selected');
      return;
    }

  
  

    const reader = new FileReader();
    reader.onload = async (evt) => {
      try {
        const data = evt.target?.result;
        
        if (!data) {
          throw new Error('Failed to read file');
        }

        const workbook = XLSX.read(data, { type: 'binary' });
        const sheetName = workbook.SheetNames[0];
        const sheet = workbook.Sheets[sheetName];
        let json = XLSX.utils.sheet_to_json(sheet) as Record<string, unknown>[];

     

        if (!json || json.length === 0) {
          throw new Error('Excel file is empty');
        }

     
        let rowsWithNumbers = json.map((row, idx) => ({
          data: row,
          originalRowNum: idx + 2, 
        }));

    
        rowsWithNumbers = rowsWithNumbers.filter(item => {
          const values = Object.values(item.data).filter(v => v !== null && v !== undefined && String(v).trim() !== '');
          return values.length > 0;
        });



        if (rowsWithNumbers.length === 0) {
          throw new Error('No valid data rows found in Excel file');
        }

     
        json = rowsWithNumbers.map(item => {
          const trimmedRow: Record<string, unknown> = {};
          Object.entries(item.data).forEach(([key, value]) => {
            trimmedRow[key.trim()] = typeof value === 'string' ? value.trim() : value;
          });
          return trimmedRow;
        });
     
        setUploadProgress(prev => ({
          ...prev,
          isUploading: true,
          currentStatus: 'validating' as const,
          detailedMessage: 'Validating Excel structure...',
          startTime: Date.now(),
        }));

        const validation = validateExcelStructure(json, categories);
        if (!validation.isValid) {
          setValidationErrors(validation.errors);
          setShowValidationDialog(true);
          setUploadProgress(prev => ({ ...prev, isUploading: false }));
          return;
        }

        if (validation.errors.length > 0) {
          setValidationErrors(validation.errors);
        }

      
        const duplicates = detectDuplicates(json);
        if (duplicates.skus.size > 0 || duplicates.names.size > 0) {
          const dupErrors: ValidationError[] = [];
          duplicates.skus.forEach((rows, sku) => {
            dupErrors.push({
              message: `Duplicate SKU "${sku}" found in rows: ${Array.from(rows).join(', ')}`,
              type: 'warning',
            });
          });
          duplicates.names.forEach((rows, name) => {
            dupErrors.push({
              message: `Duplicate product name "${name}" found in rows: ${Array.from(rows).join(', ')}`,
              type: 'warning',
            });
          });
          setValidationErrors(prev => [...prev, ...dupErrors]);
        }

        if (cancelUploadRef.current) {
          setUploadProgress(prev => ({ ...prev, isUploading: false }));
          return;
        }

    
        const missingCategories = new Set<string>();
        json.forEach(row => {
          const categoryName = String((row as Record<string, unknown>)['Category Name'] || '').trim();
          if (categoryName && !categories.some(c => c.name.toLowerCase() === categoryName.toLowerCase())) {
            missingCategories.add(categoryName);
          }
        });

      
        if (missingCategories.size > 0) {
          setUploadProgress(prev => ({
            ...prev,
            isUploading: true,
            currentStatus: 'validating' as const,
            detailedMessage: 'Auto-creating missing categories...',
          }));
          
          for (const categoryName of missingCategories) {
            try {
              const createRes = await fetch(
                `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/categories`,
                {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                  },
                  body: JSON.stringify({ name: categoryName }),
                }
              );
              if (createRes.ok) {
                const created = await createRes.json();
                setCategories(prev => [created, ...prev]);
                toast.success(`Auto-created category: ${categoryName}`);
              }
            } catch (err) {
              console.warn(`⚠️ Failed to auto-create category: ${categoryName}`, err);
            }
          }
        }

        setUploadProgress({
          current: 0,
          total: json.length,
          isUploading: true,
          currentStatus: 'processing' as const,
          detailedMessage: 'Processing products...',
          startTime: Date.now(),
          estimatedTime: 0,
        });

        const seenSkus = new Set<string>();
        const barcodeSet = new Set<string>();
        const failedRowsData: Record<string, unknown>[] = [];
        let successCount = 0;

        for (let i = 0; i < rowsWithNumbers.length; i++) {
          if (cancelUploadRef.current) break;

          const rowNumber = rowsWithNumbers[i].originalRowNum;
          const row = rowsWithNumbers[i].data;
          const productRow = row as ExcelProductRow;

          const elapsed = Date.now() - uploadProgress.startTime;
          const avgTimePerRow = elapsed / (i + 1);
          const remainingRows = rowsWithNumbers.length - (i + 1);
          const estimatedTime = avgTimePerRow * remainingRows;

          setUploadProgress(prev => ({
            ...prev,
            current: i + 1,
            estimatedTime,
            detailedMessage: `Processing row ${rowNumber} (${i + 1}/${rowsWithNumbers.length}) - ETA: ${Math.ceil(estimatedTime / 1000)}s`,
          }));

          try {

            const categoryName = String(productRow['Category Name'] || '').trim();
            
            if (!categoryName) {
              throw new Error(`Row ${rowNumber}: Category Name is empty or missing`);
            }

            let category = categories.find(
              c => c.name.toLowerCase() === categoryName.toLowerCase()
            );

            if (!category && missingCategories.has(categoryName)) {
              try {
                const createRes = await fetch(
                  `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/categories`,
                  {
                    method: 'POST',
                    headers: {
                      'Content-Type': 'application/json',
                      Authorization: `Bearer ${token}`,
                    },
                    body: JSON.stringify({ name: productRow['Category Name'] }),
                  }
                );
                if (createRes.ok) {
                  category = await createRes.json();
                  setCategories(prev => [category!, ...prev]);
                }
              } catch {
                throw new Error(`Failed to auto-create category: ${categoryName}`);
              }
            }

            if (!category) {
              throw new Error(`Category "${categoryName}" not found`);
            }

            const images: File[] = [];

          
            if (productRow['Product Images'] && bulkImages) {
              const imageNames = productRow['Product Images'].split(',').map(n => n.trim());
              const missingImagesList: string[] = [];

              for (const imageName of imageNames) {
          
                let file = Array.from(bulkImages).find(
                  f => f.name.toLowerCase() === imageName.toLowerCase()
                );

             
                if (!file) {
                  file = fuzzyMatchFilename(imageName, Array.from(bulkImages));
                }

                if (file) {
            
                  const imageCategory = bulkImageCategories.find(ic => ic.fileName === file!.name);
                  const category = imageCategory?.category || 'both';
                  
           
                  if (category === 'product' || category === 'both') {
                    images.push(file);
                  } else {
                 
                    missingImagesList.push(`${imageName} (marked as variant-only)`);
                  }
                } else {
                  missingImagesList.push(imageName);
                }
              }

              if (missingImagesList.length > 0) {
                setMissingImages(prev => [
                  ...prev,
                  {
                    rowNumber,
                    productName: productRow['Product Name'],
                    missingImages: missingImagesList,
                  },
                ]);
              }
            }

            let parsedVariants: ExcelVariant[] = [];

        
            if (productRow['Variants']) {
              const validation = validateVariantJSON(String(productRow['Variants']));
              if (!validation.isValid) {
                throw new Error(`Invalid Variants for row ${rowNumber}: ${validation.error}`);
              }
              parsedVariants = validation.parsed || [];

            
              if (bulkImages && bulkImages.length > 0) {
                const variantMissingImages: string[] = [];
                for (const variant of parsedVariants) {
                  if (variant.images) {
                    const variantImageNames = variant.images.split(',').map(n => n.trim());
                    for (const imgName of variantImageNames) {
                      const exists = Array.from(bulkImages).some(
                        f => f.name.toLowerCase() === imgName.toLowerCase()
                      );
                      if (!exists) {
                        const fuzzy = fuzzyMatchFilename(imgName, Array.from(bulkImages));
                        if (!fuzzy) {
                          variantMissingImages.push(imgName);
                        }
                      }
                    }
                  }
                }
                
                if (variantMissingImages.length > 0) {
                  setMissingImages(prev => [
                    ...prev,
                    {
                      rowNumber,
                      productName: productRow['Product Name'],
                      missingImages: variantMissingImages,
                    },
                  ]);
                }
              } else if (parsedVariants.some(v => v.images)) {
          
                const variantImageNames = parsedVariants
                  .filter(v => v.images)
                  .flatMap(v => v.images?.split(',').map(n => n.trim()) || []);
                
                setMissingImages(prev => [
                  ...prev,
                  {
                    rowNumber,
                    productName: productRow['Product Name'],
                    missingImages: variantImageNames,
                  },
                ]);
              }
            }

            const rowHasVariations = productRow['Has Variations'] === 'Yes';

         
            const baseSkuProvided = !!(productRow['Base SKU'] && productRow['Base SKU'].trim());
            const baseSku = (productRow['Base SKU'] && productRow['Base SKU'].trim()) || generateUniqueSKU(productRow['Product Name'], '');
            const autoGeneratedBaseSku = !baseSkuProvided;

            const variants: CreateProductPayload['variants'] =
              rowHasVariations && parsedVariants.length > 0
                ? parsedVariants.map((v: ExcelVariant) => {
                    const variantImages: File[] = [];

                    if (v.images && bulkImages) {
                      v.images.split(',').forEach(img => {
                        const imageName = img.trim();
                        let file = Array.from(bulkImages).find(
                          f => f.name.toLowerCase() === imageName.toLowerCase()
                        );
                        if (!file) {
                          file = fuzzyMatchFilename(imageName, Array.from(bulkImages));
                        }
                        if (file) {
                        
                          const imageCategory = bulkImageCategories.find(ic => ic.fileName === file!.name);
                          const category = imageCategory?.category || 'both';
                          
                         
                          if (category === 'variant' || category === 'both') {
                            variantImages.push(file);
                          }
                        }
                      });
                    }

                    return {
                      name: v.name || 'Default',
                      sku: (v.sku && v.sku.trim()) || generateUniqueSKU(v.name, baseSku),
                      barcode: (v.barcode && v.barcode.trim()) || generateUniqueBarcode(),
                      costPrice: v.costPrice ?? 0,
                      sellingPrice: v.sellingPrice ?? 0,
                      quantity: v.quantity ?? 0,
                      threshold: v.threshold ?? 0,
                      images: variantImages,
                    };
                  })
                : (() => {
                 
                    const barcodeValue = productRow['Barcode'] ? String(productRow['Barcode']).trim() : '';
                    const barcodeProvided = !!barcodeValue;
                    const barcode = barcodeProvided ? barcodeValue : generateUniqueBarcode();
                    
                    return [
                      {
                        name: 'Default',
                        sku: baseSku,
                        barcode: barcode,
                        costPrice: productRow['Cost Price'] ? Number(productRow['Cost Price']) : 0,
            sellingPrice: productRow['Selling Price'] ? Number(productRow['Selling Price']) : 0,
            quantity: productRow['Quantity'] ? Number(productRow['Quantity']) : 0,
            threshold: productRow['Threshold'] ? Number(productRow['Threshold']) : 0,
                        images: images,
                      },
                    ];
                  })();

         
            variants.forEach(v => {
              if (seenSkus.has(v.sku)) {
                throw new Error(`Duplicate SKU: ${v.sku}`);
              }
              if (barcodeSet.has(v.barcode)) {
                throw new Error(`Duplicate barcode: ${v.barcode}`);
              }
              seenSkus.add(v.sku);
              barcodeSet.add(v.barcode);
            });

            const payload: CreateProductPayload = {
              name: productRow['Product Name'],
              brand: productRow['Brand'],
              categoryId: category.id,
              unit: productRow['Unit'],
              taxable: productRow['Taxable'] === 'Yes',
              description: productRow['Description'],
              images: images,
              hasVariations: rowHasVariations,
              baseSku: baseSku,
              variants,
            };

            setUploadProgress(prev => ({
              ...prev,
              currentStatus: 'uploading' as const,
              detailedMessage: `Uploading ${payload.name}...`,
            }));

            const formData = buildProductFormData(payload);
            if (!token) throw new Error('No authentication token found');

          

            const productRes = await fetch(
              `${process.env.NEXT_PUBLIC_API_BASE_URL}/products/with-variants`,
              {
                method: 'POST',
                body: formData,
                headers: { Authorization: `Bearer ${token}` },
              }
            );

       

            if (!productRes.ok) {
              const err = await productRes.json();
              console.error('Server error response:', err);
              throw new Error(err.message || 'Failed to create product');
            }

            let responseData: ApiResponse = {};
            try {
              const responseText = await productRes.text();
          
              
              if (responseText) {
                responseData = JSON.parse(responseText) as ApiResponse;
              }
            } catch (parseErr) {
              console.error('Failed to parse response:', parseErr);
              responseData = {};
            }

        

       
            const generatedInfo: string[] = [];
            if (autoGeneratedBaseSku) {
              generatedInfo.push(`SKU: ${baseSku}`);
            }
            const barcodeProvided = !!(productRow['Barcode'] && productRow['Barcode'].trim());
            if (!barcodeProvided) {
              generatedInfo.push(`Barcode: ${variants[0]?.barcode}`);
            }

            const warningMessage = generatedInfo.length > 0 
              ? `Auto-generated: ${generatedInfo.join(', ')}` 
              : undefined;

            toast.success(`Product "${payload.name}" created 🎉`);
            
       
            const productId = responseData.product?.id || responseData.productId;
            if (productId) {
              createdProductIds.push(String(productId));
         
            } else {
              console.warn('⚠️ No product ID in response:', responseData);
            }
            
            successCount++;
            setImportReport(prev => [
              ...prev,
              {
                rowNumber,
                productName: payload.name,
                status: 'success',
                warning: warningMessage,
                autoGeneratedSku: autoGeneratedBaseSku,
                autoGeneratedBarcode: !barcodeProvided,
              },
            ]);
          } catch (err) {
            const errorMessage = err instanceof Error ? err.message : 'Unknown error';
            console.error(`❌ Error creating product at row ${rowNumber}:`, {
              productName: productRow['Product Name'],
              error: errorMessage,
              fullError: err,
            });
            failedRowsData.push(productRow);
            setImportReport(prev => [
              ...prev,
              {
                rowNumber,
                productName: productRow['Product Name'],
                status: 'failed',
                message: errorMessage,
              },
            ]);

            toast.error(`Failed to create product at row ${rowNumber}: ${errorMessage}`);
          }
        }

     
        if (failedRowsData.length > 0) {
          setFailedRows(failedRowsData);
        }

     
        const totalProcessed = successCount + failedRowsData.length;
        
     
        const autoGenCount = importReport.filter(r => r.status === 'success' && (r.autoGeneratedSku || r.autoGeneratedBarcode)).length;
        
        let detailedMessage = `Import completed: ${successCount}/${totalProcessed} products created successfully`;
        if (autoGenCount > 0) {
          detailedMessage += ` (${autoGenCount} with auto-generated SKU/Barcode)`;
        }
        
        setUploadProgress(prev => ({
          ...prev,
          isUploading: false,
          currentStatus: 'completed' as const,
          detailedMessage: detailedMessage,
        }));

        if (failedRowsData.length === 0) {
          let successMsg = `All ${successCount} products imported successfully! 🎉`;
          if (autoGenCount > 0) {
            successMsg += ` (${autoGenCount} had auto-generated SKU/Barcode)`;
          }
          toast.success(successMsg);
        } else {
          toast.warning(
            `Import completed: ${successCount} succeeded, ${failedRowsData.length} failed. Download failed rows to retry.`
          );
        }
      } catch (err) {
        console.error('Excel upload error:', err);
        toast.error(err instanceof Error ? err.message : 'Unknown error during upload');
        setUploadProgress(prev => ({ ...prev, isUploading: false }));
      } finally {
     
        if (excelInputRef.current) {
          excelInputRef.current.value = '';
        }
      }
    };

    reader.readAsBinaryString(file);
  }


  const downloadFailedRows = () => {
    if (failedRows.length === 0) return;
    const worksheet = XLSX.utils.json_to_sheet(failedRows);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Failed Rows');
    XLSX.writeFile(workbook, 'failed-products.xlsx');
  };

 
  const downloadMissingImagesList = () => {
    if (missingImages.length === 0) return;
    const data = missingImages.map(item => ({
      'Row Number': item.rowNumber,
      'Product Name': item.productName,
      'Missing Images': item.missingImages.join(', '),
    }));
    const worksheet = XLSX.utils.json_to_sheet(data);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Missing Images');
    XLSX.writeFile(workbook, 'missing-images.xlsx');
  };

 
  

    function abbreviateWord(word: string): string {
  if (word.length <= 3) return word.toUpperCase();
  return word.slice(0, 4).toUpperCase();
}

const downloadErrorReport = () => {
  const worksheet = XLSX.utils.json_to_sheet(importReport);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Import Report");
  XLSX.writeFile(workbook, "import-report.xlsx");
};


function generateBaseSku(
  brand: string,
  productName: string
): string {
  if (!brand || !productName) return "";

  const brandPart = brand.trim().toUpperCase();

  const productPart = productName
    .trim()
    .split(/\s+/)
    .map(abbreviateWord)
    .join("-");

  return `${brandPart}-${productPart}`;
}

const computedBaseSku: string = generateBaseSku(brand, productName);

const baseSku: string =
  customBaseSku !== null ? customBaseSku : computedBaseSku;

const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
  const files = e.target.files;
  if (!files) return;

  setProductImages(prev => [
    ...prev,
    ...Array.from(files),
  ]);
   if (imageInputRef.current) {
    imageInputRef.current.value = "";
  }
};



  const removeImage = (index: number) => {
    setProductImages(prev => prev.filter((_, i) => i !== index));
  };

  

const addAttribute = () => {
  setAttributes(prev => [
    ...prev,
    {
      id: crypto.randomUUID(),
      name: "",
      values: [],
      attributeId: undefined,
    },
  ]);
};

const generateVariations = () => {
  setVariantsGenerated(true);
  syncVariations();
  toast.success("Variants generated");
};


  const updateVariation = (
  id: number,
  field: keyof Variation,
  value: number
) => {
  setVariations(prev =>
    prev.map(v =>
      v.id === id ? { ...v, [field]: value } : v
    )
  );
};

const updateVariantText = (
  id: number,
  field: "barcode",
  value: string
) => {
  setVariations(prev =>
    prev.map(v =>
      v.id === id ? { ...v, [field]: value } : v
    )
  );
};


const updateAttributeName = (index: number, name: string) => {
  setAttributes(prev => {
     const copy = [...prev];

    const matched = availableAttributes.find(
      a => a.name.toLowerCase() === name.trim().toLowerCase()
    );

    copy[index].name = name;


 if (matched) {
     copy[index].attributeId = matched.id;

  if (copy[index].values.length === 0 && matched.values?.length) {
    copy[index].values = matched.values.map(v => v.value);
  }
    } else {
      copy[index].attributeId = undefined;
    }

    return copy;
  });
};

const addAttributeValue = async (attrIndex: number, value: string) => {
  if (!value.trim()) return;

  const attr = attributes[attrIndex];

 
  if (
    attr.values.some(
      v => v.toLowerCase() === value.toLowerCase()
    )
  ) {
    toast.error("Value already exists");
    return;
  }

 
  if (attr.attributeId) {
    try {
      const token = localStorage.getItem("adminToken");
      if (!token) throw new Error("No auth token");

      const res = await fetch(
        `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/attributes/${attr.attributeId}/values`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({ value }),
        }
      );

      if (!res.ok) {
        throw new Error("Failed to save attribute value");
      }
    } catch (err) {
      toast.error("Could not save attribute value");
      console.error(err);
      return;
    }
  }


  setAttributes(prev => {
    const next = prev.map((a, i) =>
      i === attrIndex
        ? { ...a, values: [...a.values, value] }
        : a
    );

    if (variantsGenerated) {
      queueMicrotask(syncVariations);
    }

    return next;
  });
};



const removeAttribute = (index: number) => {
  setAttributes(prev => {
    const next = prev.filter((_, i) => i !== index);

    if (variantsGenerated) {
      queueMicrotask(syncVariations);
    }

    return next;
  });
};


const removeAttributeValue = (attrIndex: number, valueIndex: number) => {
  setAttributes(prev => {
    const next = prev.map((attr, i) =>
      i === attrIndex
        ? {
            ...attr,
            values: attr.values.filter((_, v) => v !== valueIndex),
          }
        : attr
    );

    if (variantsGenerated) {
      queueMicrotask(syncVariations);
    }

    return next;
  });
};



function generateCombinations(attributes: { name: string; values: string[] }[]) {
  const validAttrs = attributes.filter(
    a => a.name.trim() && a.values.length > 0
  );

  if (validAttrs.length === 0) return [];

  return validAttrs.reduce<string[][]>(
    (acc, attr) =>
      acc.flatMap(prev =>
        attr.values.map(value => [...prev, value])
      ),
    [[]]
  );
}

function buildVariations(
  attributes: { name: string; values: string[] }[],
  existing: Variation[],
  baseSku: string
): Variation[] {
  const combos = generateCombinations(attributes);

  return combos.map((combo, index) => {
    const name = combo.join("-");

      const variantPart = combo
      .map(v => v.toUpperCase())
      .join("-");

    const sku = `${variantPart}-${baseSku}`;

    const existingVariant = existing.find(v => v.name === name);

    return {
      id: existingVariant?.id ?? Date.now() + index,
      name,
      sku,
      barcode: existingVariant?.barcode ?? generateUniqueBarcode(),
      costPrice: existingVariant?.costPrice ?? 0,
      sellingPrice: existingVariant?.sellingPrice ?? 0,
      quantity: existingVariant?.quantity ?? 0,
      threshold: existingVariant?.threshold ?? 0,
      images: existingVariant?.images ?? [],
    };
  });
}

const resetForm = () => {
  setProductName("");
  setBrand("");
  setCategoryId("");
  setDescription("");
  setTaxable(false);
  setUnit("Pieces");
  setCustomBaseSku(null);

  setProductImages([]);
  setSingleBarcode("");

  setHasVariations(false);
  setVariantsGenerated(false);
  setVariations([]);
  setAttributes([]);

  setNewCategoryName("");
};



const syncVariations = () => {
  setVariations(prev => buildVariations(attributes, prev, baseSku));
};


const handleBulkImagesChange = (e: React.ChangeEvent<HTMLInputElement>) => {
  try {
    if (!e.target.files || e.target.files.length === 0) {
      return;
    }
    
    const newFiles = Array.from(e.target.files);
    
    const dataTransfer = new DataTransfer();
    if (bulkImages) {
      Array.from(bulkImages).forEach(file => dataTransfer.items.add(file));
    }
    newFiles.forEach(file => dataTransfer.items.add(file));
    
    setBulkImages(dataTransfer.files);
    
    setBulkImageCategories(prev => {
      const updated = [...prev];
      newFiles.forEach(file => {
        if (!updated.find(ic => ic.fileName === file.name)) {
          updated.push({ fileName: file.name, category: 'both' });
        }
      });
      return updated;
    });

 
    e.target.value = '';
    
  } catch (err) {
    console.error('Error handling bulk images:', err);
    toast.error('Error uploading images');
  }
};

const downloadExcelTemplate = () => {

 const template = [
    {
      "Product Name": "Classic T-Shirt",
      "Brand": "Nike",
      "Category Name": "Clothing",
      "Unit": "Pieces",
      "Taxable": "Yes",
      "Description": "Premium cotton t-shirt with crew neck",
      "Has Variations": "Yes",
      "Base SKU": "NIKE-TSHIRT",
      "Cost Price": "",
      "Selling Price": "",
      "Quantity": "",
      "Threshold": "",
      "Barcode": "",
      "Product Images": "shirt1.jpg,shirt2.jpg",
      "Variants": JSON.stringify(
        [
          {
            name: "Red-Small",
            sku: "RED-SM-TSHIRT",
            barcode: "BAR-RED-SM",
            costPrice: 2500,
            sellingPrice: 4000,
            quantity: 30,
            threshold: 5,
            images: "red-small.jpg",
          },
          {
            name: "Red-Large",
            sku: "RED-LG-TSHIRT",
            barcode: "BAR-RED-LG",
            costPrice: 3000,
            sellingPrice: 4500,
            quantity: 20,
            threshold: 5,
            images: "red-large.jpg",
          },
          {
            name: "Blue-Small",
            sku: "BLUE-SM-TSHIRT",
            barcode: "BAR-BLUE-SM",
            costPrice: 2500,
            sellingPrice: 4000,
            quantity: 25,
            threshold: 5,
            images: "blue-small.jpg",
          },
        ],
        null,
        2
      ),
    },
    {
      "Product Name": "Plain Hoodie",
      "Brand": "Adidas",
      "Category Name": "Clothing",
      "Unit": "Pieces",
      "Taxable": "No",
      "Description": "Warm winter hoodie with zip closure",
      "Has Variations": "No",
      "Base SKU": "ADI-HOODIE",
      "Cost Price": "3500",
      "Selling Price": "5500",
      "Quantity": "50",
      "Threshold": "10",
      "Barcode": "BAR-HOODIE-001",
      "Product Images": "hoodie1.jpg,hoodie2.jpg",
      "Variants": "",
    },
    {
      "Product Name": "Sports Shoes",
      "Brand": "Puma",
      "Category Name": "Footwear",
      "Unit": "Pairs",
      "Taxable": "Yes",
      "Description": "Lightweight running shoes with cushioning",
      "Has Variations": "Yes",
      "Base SKU": "PUMA-SHOES",
      "Cost Price": "",
      "Selling Price": "",
      "Quantity": "",
      "Threshold": "",
      "Barcode": "",
      "Product Images": "shoes1.jpg",
      "Variants": JSON.stringify(
        [
          {
            name: "Size-7",
            sku: "PUMA-SHOES-7",
            barcode: "BAR-SHOES-7",
            costPrice: 4000,
            sellingPrice: 6500,
            quantity: 15,
            threshold: 3,
            images: "",
          },
          {
            name: "Size-9",
            sku: "PUMA-SHOES-9",
            barcode: "BAR-SHOES-9",
            costPrice: 4000,
            sellingPrice: 6500,
            quantity: 18,
            threshold: 3,
            images: "",
          },
        ],
        null,
        2
      ),
    },
    {
      "Product Name": "Basic Cotton Socks",
      "Brand": "Puma",
      "Category Name": "Accessories",
      "Unit": "Pairs",
      "Taxable": "Yes",
      "Description": "Comfortable everyday socks",
      "Has Variations": "No",
      "Base SKU": "PUMA-SOCKS",
      "Cost Price": "500",
      "Selling Price": "1000",
      "Quantity": "200",
      "Threshold": "20",
      "Barcode": "BAR-SOCKS-001",
      "Product Images": "socks1.jpg",
      "Variants": "",
    },
  ];

 const worksheet = XLSX.utils.json_to_sheet(template);
  
 
  const instructionsSheet = XLSX.utils.json_to_sheet([
    {
      Column: "Product Name",
      Required: "Yes",
      Type: "Text",
      "Notes": "Name of the product",
      "Example": "Classic T-Shirt",
    },
    {
      Column: "Brand",
      Required: "Yes",
      Type: "Text",
      "Notes": "Brand name",
      "Example": "Nike",
    },
    {
      Column: "Category Name",
      Required: "Yes",
      Type: "Text",
      "Notes": "Must exist in system or will be auto-created",
      "Example": "Clothing, Footwear, Electronics",
    },
    {
      Column: "Unit",
      Required: "Yes",
      Type: "Text",
      "Notes": "Unit of measurement",
      "Example": "Pieces, Pairs, Kg, Meters",
    },
    {
      Column: "Taxable",
      Required: "Yes",
      Type: "Yes/No",
      "Notes": "Is product taxable?",
      "Example": "Yes or No",
    },
    {
      Column: "Description",
      Required: "Yes",
      Type: "Text",
      "Notes": "Product description",
      "Example": "Premium quality with...",
    },
    {
      Column: "Has Variations",
      Required: "Yes",
      Type: "Yes/No",
      "Notes": "Does product have variants? (Color, Size, etc.)",
      "Example": "Yes or No",
    },
    {
      Column: "Base SKU",
      Required: "Yes",
      Type: "Text",
      "Notes": "Base stock keeping unit (must be unique)",
      "Example": "NIKE-TSHIRT",
    },
    {
      Column: "Cost Price",
      Required: "Conditional",
      Type: "Number",
      "Notes": "Only for products WITHOUT variations (Has Variations = No)",
      "Example": "2500",
    },
    {
      Column: "Selling Price",
      Required: "Conditional",
      Type: "Number",
      "Notes": "Only for products WITHOUT variations (Has Variations = No)",
      "Example": "5500",
    },
    {
      Column: "Quantity",
      Required: "Conditional",
      Type: "Number",
      "Notes": "Only for products WITHOUT variations (Has Variations = No)",
      "Example": "50",
    },
    {
      Column: "Threshold",
      Required: "Conditional",
      Type: "Number",
      "Notes": "Low stock threshold - Only for products WITHOUT variations",
      "Example": "10",
    },
    {
      Column: "Barcode",
      Required: "Conditional",
      Type: "Text",
      "Notes": "Optional. Auto-generated if not provided. Only for products WITHOUT variations",
      "Example": "BAR-HOODIE-001",
    },
    {
      Column: "Product Images",
      Required: "No",
      Type: "Text",
      "Notes": "Comma-separated filenames (must upload files in bulk images)",
      "Example": "shirt1.jpg,shirt2.jpg",
    },
    {
      Column: "Variants",
      Required: "Conditional",
      Type: "JSON Array",
      "Notes": "Only if 'Has Variations' = Yes. Array with name, sku, barcode, costPrice, sellingPrice, quantity, threshold, images",
      "Example": '[{"name":"Red-L","sku":"RED-TSHIRT","barcode":"...","costPrice":2500,"sellingPrice":4000,"quantity":30,"threshold":5,"images":"red.jpg"}]',
    },
  ]);


  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Template Examples");
  XLSX.utils.book_append_sheet(workbook, instructionsSheet, "Column Guide");

  XLSX.writeFile(workbook, "product-bulk-upload-template.xlsx");
};

const removeVariant = (id: number) => {
  setVariations(prev => {
    const next = prev.filter(v => v.id !== id);

    if (next.length === 0) {
      setVariantsGenerated(false);
    }

    return next;
  });
};


const attributesLocked = variantsGenerated && variations.length > 0;

const handleVariantImageUpload = (id: number, files: FileList | null) => {
  if (!files) return;

  setVariations(prev =>
    prev.map(v =>
      v.id === id
        ? { ...v, images: [...v.images, ...Array.from(files)] }
        : v
    )
  );
};

  const handleGenerateBarcode = () => {
    const newBarcode = generateUniqueBarcode();
    setSingleBarcode(newBarcode);
    toast.success('Barcode generated');
  };


  const handleRegenerateVariantBarcode = (variantId: number) => {
    const newBarcode = generateUniqueBarcode();
    updateVariantText(variantId, "barcode", newBarcode);
    toast.success('Barcode regenerated');
  };

  const buildCreateProductPayload = (): CreateProductPayload => {
  if (!productName || !brand) {
    throw new Error("Missing required fields");
  }

  if (hasVariations) {
    return {
      name: productName,
      brand,
      categoryId,
      unit,
      taxable,
      description,
      images: productImages,
      hasVariations: true,
      baseSku,

      variants: variations.map(v => ({
        name: v.name,
        sku: v.sku,
        barcode: v.barcode,
        costPrice: v.costPrice,
        sellingPrice: v.sellingPrice,
        quantity: v.quantity,
        threshold: v.threshold,
        images: v.images as File[], 
      })),
    };
  }

 return {
  name: productName,
  brand,
  categoryId,
  unit,
  taxable,
  description,
  images: productImages,
  hasVariations: false,
  baseSku,

  variants: [
    {
      name: "Default",
      sku: baseSku,
      barcode: singleBarcode || generateUniqueBarcode(),
      costPrice: singleStock.costPrice,
      sellingPrice: singleStock.sellingPrice,
      quantity: singleStock.quantity,
      threshold: singleStock.threshold,
      images: [],
    },
  ],
};

};

const buildProductFormData = (payload: CreateProductPayload) => {
  const formData = new FormData();

  formData.append("category_id", payload.categoryId);
  formData.append("name", payload.name);
  formData.append("brand", payload.brand);
  formData.append("description", payload.description);
  formData.append("base_sku", payload.baseSku);
  formData.append("unit", payload.unit);
  formData.append("taxable", String(payload.taxable));
  formData.append("hasVariation", JSON.stringify(payload.hasVariations));


  if (payload.images.length > 0) {
    formData.append("product_main_image", payload.images[0]);

    payload.images.slice(1).forEach(file => {
      formData.append("product_additional_image_", file);
    });
  }

  const validAttributes = attributes.filter(
    a => a.name.trim() && a.values.length > 0
  );

  if (payload.hasVariations && validAttributes.length > 0) {
    formData.append(
      "attributes",
      JSON.stringify(
        validAttributes.map(a => ({
          name: a.name,
          values: a.values,
        }))
      )
    );
  }

 
  const variantsJson = payload.variants.map(v => ({
    sku: v.sku,
    barcode: v.barcode,
    cost_price: v.costPrice,
    selling_price: v.sellingPrice,
    quantity: v.quantity,
    threshold: v.threshold,
  }));

  formData.append("variants", JSON.stringify(variantsJson));


  let variantImageCount = 0;
  payload.variants.forEach((variant, index) => {
    if (variant.images && variant.images.length > 0) {
      variant.images.forEach((file) => {
      
        formData.append(`variants[${index}][image_url]`, file);
        variantImageCount++;
      });
    }
  });
  toast.info(`Prepared FormData with ${payload.images.length} product images and ${variantImageCount} variant images`);
  return formData;
};


  return (
    <div className="space-y-6 bg-white">
      <Card className='bg-white border-2 border-gray-900 rounded-2xl text-gray-900 shadow-lg'>
        <CardHeader>
          <CardTitle className='text-gray-900'>Add New Product</CardTitle>
          <CardDescription className='text-gray-900'>
            Fill in the product details and variations
          </CardDescription>
        </CardHeader>
        <CardContent>
      <div className="mb-8">
  <div className="flex flex-wrap gap-3 items-center bg-gray-50 border border-gray-200 rounded-xl p-4 shadow-sm">
    <Button
      onClick={downloadErrorReport}
      variant="outline"
      className="flex items-center gap-2"
      disabled={importReport.length === 0}
      title={importReport.length === 0 ? "No import report yet" : ""}
    >
      <Loader className="h-4 w-4 text-gray-500" />
      Download Import Report
    </Button>

    <Button
      className="flex items-center gap-2 bg-blue-500 hover:bg-blue-600 text-white"
      asChild
    >
      <label className="cursor-pointer">
        <Plus className="h-4 w-4" />
        Bulk Upload (Excel)
        <input
          key={importReport.length}
          ref={excelInputRef}
          type="file"
          accept=".xlsx,.xls"
          className="hidden"
          onChange={handleExcelUpload}
        />
      </label>
    </Button>

    <Button
      variant="outline"
      className="flex items-center gap-2"
      onClick={downloadExcelTemplate}
    >
      <Hash className="h-4 w-4" />
      Download Excel Template
    </Button>

<Button
  onClick={(e) => {
    e.preventDefault();
    e.stopPropagation();
    bulkImagesInputRef.current?.click();
  }}
  variant="secondary"
  className="flex items-center gap-2"
>
      <ImageIcon className="h-4 w-4" />
      {bulkImages && bulkImages.length > 0 ? (
        <>
          Add More Images
          <span className="bg-blue-500 text-white text-xs rounded-full px-2 py-1">
            {bulkImages.length} selected
          </span>
        </>
      ) : (
        <>
          Select Bulk Images
          <span className="text-xs text-gray-500 ml-auto">(multiple)</span>
        </>
      )}
    </Button>
<input
  ref={bulkImagesInputRef}
  type="file"
  multiple
  accept="image/*"
  className="hidden"
  onChange={handleBulkImagesChange}
/>

    {uploadProgress.isUploading && (
      <div className="flex items-center gap-3 ml-auto">
        <div className="text-sm text-blue-700 font-medium">
          <div className="flex items-center gap-2">
            <Loader className="h-4 w-4 animate-spin" />
            {uploadProgress.currentStatus.charAt(0).toUpperCase() + uploadProgress.currentStatus.slice(1)}
          </div>
          <div className="text-xs text-gray-600 mt-1">{uploadProgress.detailedMessage}</div>
          <div className="w-32 h-2 bg-gray-200 rounded-full mt-2 overflow-hidden">
            <div
              className="h-full bg-blue-500 transition-all"
              style={{
                width: `${uploadProgress.total > 0 ? (uploadProgress.current / uploadProgress.total) * 100 : 0}%`,
              }}
            />
          </div>
        </div>
        <Button
          variant="destructive"
          size="sm"
          onClick={() => {
            cancelUploadRef.current = true;
          }}
        >
          Cancel
        </Button>
      </div>
    )}

    {failedRows.length > 0 && !uploadProgress.isUploading && (
      <Button
        onClick={downloadFailedRows}
        className="flex items-center gap-2 bg-orange-500 hover:bg-orange-600 text-white"
      >
        <Loader className="h-4 w-4" />
        Download Failed Rows
      </Button>
    )}

    {missingImages.length > 0 && !uploadProgress.isUploading && (
      <Button
        onClick={downloadMissingImagesList}
        className="flex items-center gap-2 bg-yellow-500 hover:bg-yellow-600 text-white"
      >
        <ImageIcon className="h-4 w-4" />
        Missing Images ({missingImages.length})
      </Button>
    )}
  </div>
</div>

{/* Debug: Show image count if bulkImages exists */}
{bulkImages && bulkImages.length > 0 && (
  <div className="bg-green-100 border border-green-500 p-2 rounded text-sm text-green-800 mt-4">
    ✓ {bulkImages.length} image(s) loaded in state
  </div>
)}

{/* Bulk Images Preview Section */}
{bulkImages && bulkImages.length > 0 && (
  <Card className="bg-white border-2 border-gray-900 rounded-2xl shadow-lg mt-8">
    <CardHeader>
      <div className="flex items-center justify-between">
        <div>
          <CardTitle className="text-gray-900">Uploaded Bulk Images</CardTitle>
          <CardDescription className="text-gray-600">
            {bulkImages.length} image{bulkImages.length !== 1 ? 's' : ''} - Click buttons to categorize each image
          </CardDescription>
        </div>
        <Button
          variant="destructive"
          size="sm"
          onClick={() => {
            setBulkImages(null);
            setBulkImageCategories([]);
            if (bulkImagesInputRef.current) {
              bulkImagesInputRef.current.value = '';
            }
          }}
        >
          Clear All
        </Button>
      </div>
    </CardHeader>
    <CardContent>
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 gap-4">
        {Array.from(bulkImages).map((file, index) => {
          const imageCategory = bulkImageCategories.find(ic => ic.fileName === file.name);
          const category = imageCategory?.category || 'both';
          
          return (
            <div key={index} className="flex flex-col gap-2">
              <div className="relative group">
                <div className="aspect-square rounded-lg overflow-hidden bg-gray-100 border-2 border-gray-300">
                  <Image
                    width={150}
                    height={150}
                    src={URL.createObjectURL(file)}
                    alt={file.name}
                    className="w-full h-full object-cover"
                  />
                </div>
                <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity rounded-lg flex items-center justify-center">
                  <Button
                    size="icon"
                    variant="destructive"
                    className="h-6 w-6"
                    onClick={() => {
                      if (bulkImages) {
                        const dataTransfer = new DataTransfer();
                        Array.from(bulkImages).forEach((f, i) => {
                          if (i !== index) {
                            dataTransfer.items.add(f);
                          }
                        });
                        setBulkImages(dataTransfer.files);
                        setBulkImageCategories(prev => 
                          prev.filter(ic => ic.fileName !== file.name)
                        );
                      }
                    }}
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              </div>
              <div className="text-xs text-gray-700 truncate" title={file.name}>
                {file.name}
              </div>
              <div className="flex flex-col gap-1 text-xs">
                <Button
                  variant={category === 'product' ? 'default' : 'outline'}
                  size="sm"
                  className="h-7 text-xs text-black font-medium"
                  onClick={() => 
                    setBulkImageCategories(prev => {
                      const updated = prev.filter(ic => ic.fileName !== file.name);
                      updated.push({ fileName: file.name, category: 'product' });
                      return updated;
                    })
                  }
                >
                  📦 Product
                </Button>
                <Button
                  variant={category === 'variant' ? 'default' : 'outline'}
                  size="sm"
                  className="h-7 text-xs text-black font-medium"
                  onClick={() => 
                    setBulkImageCategories(prev => {
                      const updated = prev.filter(ic => ic.fileName !== file.name);
                      updated.push({ fileName: file.name, category: 'variant' });
                      return updated;
                    })
                  }
                >
                  🎨 Variant
                </Button>
                <Button
                  variant={category === 'both' ? 'default' : 'outline'}
                  size="sm"
                  className="h-7 text-xs text-black font-medium"
                  onClick={() => 
                    setBulkImageCategories(prev => {
                      const updated = prev.filter(ic => ic.fileName !== file.name);
                      updated.push({ fileName: file.name, category: 'both' });
                      return updated;
                    })
                  }
                >
                  ✨ Both
                </Button>
              </div>
            </div>
          );
        })}
      </div>
      <div className="mt-4 p-3 bg-blue-50 rounded-lg border border-blue-200">
        <p className="text-sm text-blue-900">
          <strong>📖 How to use:</strong> Click buttons to specify each image&apos;s purpose:
        </p>
        <ul className="text-xs text-blue-800 mt-2 space-y-1 ml-4 list-disc">
          <li><strong>📦 Product:</strong> Only use for product images in Excel</li>
          <li><strong>🎨 Variant:</strong> Only use for variant images in Excel</li>
          <li><strong>✨ Both:</strong> Can be used for both product and variant (default)</li>
        </ul>
      </div>
    </CardContent>
  </Card>
)}

{/* Feature #1: Validation Errors Dialog */}
<Dialog open={showValidationDialog} onOpenChange={setShowValidationDialog}>
  <DialogContent className="max-w-2xl max-h-96 overflow-y-auto bg-white text-gray-900">
    <DialogHeader>
      <DialogTitle className="text-red-600">Validation Errors Found</DialogTitle>
    </DialogHeader>
    <div className="space-y-3">
      {validationErrors.map((error, idx) => (
        <div
          key={idx}
          className={`p-3 rounded border-l-4 ${
            error.type === 'error'
              ? 'border-red-500 bg-red-50'
              : 'border-yellow-500 bg-yellow-50'
          }`}
        >
          <div className="font-medium text-sm">
            {error.type === 'error' ? '✗ Error' : '⚠ Warning'}
            {error.row && ` (Row ${error.row})`}
            {error.column && ` - ${error.column}`}
          </div>
          <div className="text-sm text-gray-700 mt-1">{error.message}</div>
        </div>
      ))}
    </div>
    <DialogFooter>
      <Button
        onClick={() => setShowValidationDialog(false)}
        className="bg-gray-900 text-white hover:bg-gray-800"
      >
        Close
      </Button>
    </DialogFooter>
  </DialogContent>
</Dialog>


          
          <div className="space-y-6">
       
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="space-y-4">
                <div className='flex flex-col gap-3'>
                  <Label htmlFor="productName">Product Name</Label>
                  <Input
                    id="productName"
                    value={productName}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setProductName(e.target.value)
                    }
                    className='border-gray-900 border-2 shadow-lg'
                    />
                </div>
                
               <div className='flex flex-col gap-3'>
                  <Label htmlFor="brand">Brand</Label>
                    <Input
                    id="brand"
                    value={brand}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                        setBrand(e.target.value)
                    }
                     className='border-gray-900 border-2 shadow-lg'
                    />

                </div>
                
                <div>
                  <Label className='mb-2' htmlFor="category">Category</Label>
              <Select onValueChange={setCategoryId} value={categoryId} disabled={categoriesLoading} >
                  <SelectTrigger className="border-gray-900 border-2 shadow-lg">
                    <SelectValue placeholder={categoriesLoading ? "Loading categories..." : "Select category"} />
                  </SelectTrigger>

                  <SelectContent>
                    {categoriesLoading && (
  <div className="flex items-center gap-2 text-sm text-gray-600">
    <Loader className="h-4 w-4 animate-spin" />
    Loading categories...
  </div>
)}
                   {categoriesLoading ? (
                        <div className="p-2 text-center text-sm text-gray-600">
                          Loading categories...
                        </div>
                      ) : categories.length === 0 ? (
                        <div className="p-2 text-center text-sm text-gray-600">
                          No categories available
                        </div>
                      ) : (
                        categories.map(cat => (
                          <SelectItem key={cat.id} value={cat.id}>
                            {cat.name}
                          </SelectItem>
                        ))
                      )}
                  </SelectContent>
                </Select>
                 <Button
                    variant="link"
                    size="sm"
                    className="mt-1 p-0 h-auto text-gray-900"
                    onClick={() => setCategoryModalOpen(true)}
                    disabled={categoriesLoading}
                    >
                    <Plus className="h-3 w-3 mr-1" />
                    Create new category
                    </Button>

                </div>
              </div>
              
              <div className="space-y-4">
                 <div className='flex flex-col gap-3'>
                  <Label htmlFor="unit">Unit</Label>
                  <Input id="unit" placeholder="e.g., Pieces"   className='border-gray-900 border-2 shadow-lg' value={unit} onChange={e => setUnit(e.target.value)} />
                </div>
                
                <div className='flex flex-col gap-3'>
                  <Label htmlFor="sku">Base SKU</Label>
                  <div className="flex gap-2">
                    <Input
                        id="sku"
                        value={baseSku}
                        onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                            setCustomBaseSku(e.target.value.toUpperCase())
                        }
                         className='border-gray-900 border-2 shadow-lg'
                    />

                    <Button variant="outline" size="icon">
                      <Hash className="h-4 w-4" />
                    </Button>
                  </div>
                </div>
                
                <div className="flex items-center space-x-2">
                  <Checkbox id="taxable"  checked={taxable}
  onCheckedChange={(v) => setTaxable(Boolean(v))} className='text-gray-900 border-2 border-gray-950' />
                  <Label htmlFor="taxable" className="cursor-pointer">
                    Product is taxable
                  </Label>
                </div>
              </div>
            </div>

         
            <div className="flex items-center justify-between p-4  bg-gray-900 rounded-lg">
              <div>
                <Label className="font-medium text-white">Product has variations</Label>
                <p className="text-sm text-white">
                  Enable if product comes in different colors, sizes, etc.
                </p>
              </div>
              <Switch checked={hasVariations} onCheckedChange={setHasVariations} />
            </div>

        
            <div className='flex flex-col gap-3'>
              <Label htmlFor="description">Product Description</Label>
              <Textarea 
                id="description" 
                placeholder="Describe the product features, materials, care instructions..."
                rows={4}
                className='border-gray-900 border-2 shadow-lg'
                 value={description}
                onChange={(e) => setDescription(e.target.value)}
              />
            </div>

          
           <div className='flex flex-col gap-3'>
              <Label>Product Images</Label>
              <div className="mt-2 grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">
               {productImages.map((file, index) => (
              <div key={index} className="relative group">
                <div className="aspect-square rounded-lg overflow-hidden bg-gray-100">
                  <Image
                    width={200}
                    height={200}
                    src={URL.createObjectURL(file)}
                    alt={`Product ${index + 1}`}
                    className="w-full h-full object-cover"
                  />
                </div>
               <Button
                size="icon"
                variant="destructive"
                className="absolute top-1 right-1 h-6 w-6 bg-red-500 text-white opacity-0 group-hover:opacity-100"
                onClick={() => removeImage(index)}
              >
                <Trash2 className="h-3 w-3" />
              </Button>
              </div>
            ))}

                
                <label className="cursor-pointer">
                  <input
                  ref={imageInputRef}
                    type="file"
                    multiple
                    accept="image/*"
                    className="hidden"
                    onChange={handleImageUpload}
                  />
                  <div className="aspect-square rounded-lg border-2 border-dashed border-gray-300 hover:border-gray-400 flex flex-col items-center justify-center transition-colors">
                    <ImageIcon className="h-8 w-8 text-gray-400" />
                    <span className="mt-2 text-sm text-gray-500">Add Images</span>
                  </div>
                </label>
              </div>
            </div>

            
            {hasVariations ? (
              <div className="space-y-6">
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="font-semibold text-lg">Variations Management</h3>
                    <p className="text-sm text-gray-500">Define attributes and generate variations</p>
                  </div>
                 <Button
                    onClick={generateVariations}
                    disabled={variantsGenerated}
                    className="flex items-center gap-2  bg-gray-900 text-white hover:bg-gray-800"
                    >
                    <Layers className="h-4 w-4" />
                    {variantsGenerated ? "Variants Generated" : "Generate Variations"}
                  </Button>
                </div>

               
                <Card className='bg-white border-2 border-gray-900'>
                  <CardHeader>
                    <CardTitle className="text-sm text-gray-900">Attributes</CardTitle>
                  </CardHeader>
                <CardContent className="space-y-4 text-gray-900">
                  {attributes.map((attr, index) => (
                      <AttributeItem
                          key={attr.id}
                          attr={attr}
                          index={index}
                          disabled={attributesLocked}
                          isNameLocked={Boolean(attr.attributeId)}
                          updateAttributeName={updateAttributeName}
                          addAttributeValue={addAttributeValue}
                          removeAttribute={removeAttribute}
                          removeAttributeValue={removeAttributeValue}
                      />
                      ))}


                    <Button disabled={attributesLocked}  onClick={addAttribute} className="w-full bg-gray-900 text-white hover:bg-gray-800 flex items-center justify-center">
                        <Plus className="h-4 w-4 mr-2" />
                        Add Attribute
                    </Button>
                    </CardContent>


                </Card>

               
                <Card className='bg-white border-2 border-gray-900'>
                  <CardHeader>
                    <CardTitle className="text-sm text-gray-900">Generated Variations ({variations.length})</CardTitle>
                  </CardHeader>
                  <CardContent className=" text-gray-900">
                    <div className="space-y-4">
                      {variations.map((variant) => (
                        <div key={variant.id} className="p-4 border border-gray-900 rounded-lg space-y-4">
                          <div className="flex items-center justify-between">
                            <div>
                              <div className="font-medium">{variant.name}</div>
                              <div className="text-sm text-gray-900">SKU: {variant.sku}</div>
                            </div>
                            <Button variant="ghost" size="sm"  onClick={() => removeVariant(variant.id)}>
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          </div>
                          
                          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                            <div className='flex flex-col gap-3'>
                              <Label>Cost Price</Label>
                              <Input type="number" placeholder="0.00" value={variant.costPrice}  onChange={(e) =>
    updateVariation(variant.id, "costPrice", Number(e.target.value))
  } className='border-gray-900 border-2 shadow-lg' />
                            </div>
                            <div className='flex flex-col gap-3'>
                              <Label>Selling Price</Label>
                              <Input type="number" placeholder="0.00" value={variant.sellingPrice} onChange={(e) =>
    updateVariation(variant.id, "sellingPrice", Number(e.target.value))
  } className='border-gray-900 border-2 shadow-lg' />
                            </div>
                            <div className='flex flex-col gap-3'>
                              <Label>Quantity</Label>
                              <Input type="number" placeholder="0" value={variant.quantity} onChange={(e) =>
    updateVariation(variant.id, "quantity", Number(e.target.value))
  } className='border-gray-900 border-2 shadow-lg' />
                            </div>
                            <div className='flex flex-col gap-3'>
                              <Label>Threshold</Label>
                              <Input type="number" placeholder="0" value={variant.threshold} onChange={(e) =>
    updateVariation(variant.id, "threshold", Number(e.target.value))
  } className='border-gray-900 border-2 shadow-lg' />
                            </div>

                            <div className="flex flex-col gap-3">
                              <Label>Barcode</Label>
                              <div className="flex gap-2">
                                <Input
                                  type="text"
                                  placeholder="Auto-generated"
                                  value={variant.barcode}
                                  readOnly
                                  className="border-gray-900 border-2 shadow-lg bg-gray-100 cursor-not-allowed"
                                />
                                <Button
                                  size="icon"
                                  variant="outline"
                                  onClick={() => handleRegenerateVariantBarcode(variant.id)}
                                  title="Regenerate barcode"
                                >
                                  <RefreshCw className="h-4 w-4" />
                                </Button>
                              </div>
                            </div>

                          </div>
                          
                          <div>
                            <Label>Variant Images</Label>
                            <div className="mt-2 flex gap-2">
                             <label className="cursor-pointer">
                                    <input
                                        type="file"
                                        multiple
                                        accept="image/*"
                                        className="hidden"
                                        onChange={(e) => handleVariantImageUpload(variant.id, e.target.files)}
                                    />
                                    <div className="flex bg-gray-900 text-white items-center gap-1 px-2 py-1 rounded cursor-pointer">
                                        <ImageIcon className="h-3 w-3" />
                                        Add Images
                                    </div>
                                    </label>

                            </div>
                            <div className="flex mt-2 gap-2">
                            {variant.images.map((img, i) => (
                                <div key={i} className="relative w-12 h-12 rounded overflow-hidden">
                             <Image
                              src={URL.createObjectURL(img)}
                              alt={`Variant ${i}`}
                              width={48}
                              height={48}
                              className="object-cover"
                            />
                                <button
                                    className="absolute top-0 right-0 bg-red-500 text-white rounded-full w-4 h-4 text-xs flex items-center justify-center"
                                    onClick={() => {
                                    setVariations(prev =>
                                        prev.map(v =>
                                        v.id === variant.id
                                            ? { ...v, images: v.images.filter((_, idx) => idx !== i) }
                                            : v
                                        )
                                    );
                                    }}
                                >
                                    ×
                                </button>
                                </div>
                            ))}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </CardContent>
                </Card>
              </div>
            ) : (
            
              <Card className='bg-white border-2 border-gray-900'>
                <CardHeader>
                  <CardTitle className="text-sm text-gray-900">Product Details</CardTitle>
                </CardHeader>
                <CardContent className='text-gray-900'>
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
                   <div className='flex flex-col gap-3'>
                      <Label>Cost Price</Label>
                      <Input type="number"  value={singleStock.costPrice}
  onChange={e =>
    setSingleStock(s => ({ ...s, costPrice: Number(e.target.value) }))
  } placeholder="0.00" className='border-gray-900 border-2 shadow-lg' />
                    </div>
                    <div className='flex flex-col gap-3'>
                      <Label>Selling Price</Label>
                      <Input type="number" value={singleStock.sellingPrice}
  onChange={e =>
    setSingleStock(s => ({ ...s, sellingPrice: Number(e.target.value) }))
  } placeholder="0.00" className='border-gray-900 border-2 shadow-lg' />
                    </div>
                    <div className='flex flex-col gap-3'>
                      <Label>Quantity</Label>
                      <Input type="number"  value={singleStock.quantity}
  onChange={e =>
    setSingleStock(s => ({ ...s, quantity: Number(e.target.value) }))
  }  placeholder="0" className='border-gray-900 border-2 shadow-lg' />
                    </div>
                   <div className='flex flex-col gap-3'>
                      <Label>Low Stock Threshold</Label>
                      <Input type="number" value={singleStock.threshold}
  onChange={e =>
    setSingleStock(s => ({ ...s, threshold: Number(e.target.value) }))
  } placeholder="10" className='border-gray-900 border-2 shadow-lg' />
                    </div>

                 <div className="flex flex-col gap-3">
                      <Label>Barcode</Label>
                      <div className="flex gap-2">
                        <Input
                          type="text"
                          placeholder="Auto-generated"
                          value={singleBarcode}
                          readOnly
                          className="border-gray-900 border-2 shadow-lg bg-gray-100 cursor-not-allowed"
                        />
                        <Button
                          size="icon"
                          variant="secondary"
                          onClick={handleGenerateBarcode}
                          title="Generate barcode"
                        >
                          <RefreshCw className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            )}

            <Dialog open={categoryModalOpen} onOpenChange={setCategoryModalOpen} >
                <DialogContent className="sm:max-w-md bg-white text-gray-900">
                    <DialogHeader>
                    <DialogTitle className='text-gray-900'>New Category</DialogTitle>
                    </DialogHeader>

                    <div className="space-y-4">
                    <div className="flex flex-col gap-2">
                        <Label htmlFor="categoryName">Category Name</Label>
                        <Input
                        id="categoryName"
                        placeholder="e.g. Jackets"
                        value={newCategoryName}
                        onChange={(e) => setNewCategoryName(e.target.value)}
                        className='border border-gray-900'
                        />
                    </div>
                    </div>

                    <DialogFooter className="flex gap-2">
                    <Button
                        className='bg-red-500 text-gray-900 hover:bg-red-300'
                        onClick={() => {
                        setCategoryModalOpen(false);
                        setNewCategoryName("");
                        }}
                    >
                        Cancel
                    </Button>

                    <Button
                        className="bg-gray-900 text-white hover:bg-gray-800"
                        disabled={!newCategoryName.trim()}
                        onClick={() => {
                          handleCreateCategory();
                        toast.success(`Category "${newCategoryName}" created`);
                        setCategoryModalOpen(false);
                        setNewCategoryName("");
                        }}
                    >
                        {isCreating ? (
    <>
      <Loader className="h-4 w-4 animate-spin" />
      Creating...
    </>
  ) : (
    "Create Category"
  )}
                    </Button>
                    </DialogFooter>
                </DialogContent>
                </Dialog>

           
            <div className="flex justify-end gap-3 pt-4 border-t">
  <Button
  className="bg-black hover:bg-gray-800 text-white"
   disabled={isCreating}
  onClick={async () => {
     if (isCreating) return;
      setIsCreating(true);
    try {
     
      const newAttributes = attributes.filter(a => !a.attributeId);

      if (newAttributes.length > 0) {
          const token = localStorage.getItem("adminToken");
          if (!token) {
            throw new Error("No authentication token found");
          }
        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_BASE_URL}/configure/attributes/bulk`,
          {
            method: "POST",
            headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" },
            body: JSON.stringify({
              attributes: newAttributes.map(a => ({
                name: a.name,
                values: a.values,
              })),
            }),
          }
        );

        if (!res.ok) {
          throw new Error("Failed to create attributes");
        }
      }

   
      const payload = buildCreateProductPayload();
      const formData = buildProductFormData(payload);

      const token = localStorage.getItem("adminToken"); 
        if (!token) {
          throw new Error("No authentication token found");
        }

      const productRes = await fetch(
        `${process.env.NEXT_PUBLIC_API_BASE_URL}/products/with-variants`,
        {
          method: "POST",
          body: formData,
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (!productRes.ok) {
        const err = await productRes.json();
        throw new Error(err.message || "Failed to create product");
      }

      toast.success("Product created successfully 🎉");
     
      resetForm();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setIsCreating(false);
    }
  }}

>
   {isCreating ? (
    <>
      <Loader className="h-4 w-4 animate-spin" />
      Creating...
    </>
  ) : (
    "Create Product"
  )}
</Button>

            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}